### ISSUE TITLE
file=sys.stderr syntax error

### ISSUE THREAD

**Issue by katieemelianova** [arvestad/alv#1]
I installed alv using pip install alv, after successful installation I run alv and get:

```python
  File "/usr/local/bin/alv", line 103
    print('Alv error: probably wrong input format in '+ args.infile+'. Try option -f.', file=sys.stderr)
                                                                                            ^
SyntaxError: invalid syntax
```

I'm not sure if it's related to this issue?:
https://stackoverflow.com/questions/27472194/syntax-error-whenever-i-try-to-use-sys-stderr

**Comment by arvestad** [comment]
What is the actual error message?

Are you sure you are running python3? Can you please run `python --version`?

**Comment by katieemelianova** [comment]
I'm running 2.7, I didn't see py3 as a requirement anywhere obvious though - will update my python in this case. Thanks.

**Comment by katieemelianova** [comment]
(sorry I just updated my comment - I hadn't pasted the whole error message the first time)

**Comment by arvestad** [comment]
I highly recommend migrating to using virtual environments! I use anaconda.com's community service (see https://www.anaconda.com/community/). It is the easiest to use virtual python environment I have tried. 

How did you install alv? I assumed that "pip install alv" would protest for you, since I have set python3 as a requisite.

**Comment by katieemelianova** [comment]
Nope

**Comment by katieemelianova** [comment]
No, it doesnt. I am running python 2.7, and I followed the instructions on the github page. 

I installed using 'pip install alv' and this does not error. 

In that case, I would suggest fixing that so that the installation instructions work, otherwise tell the user of the prerequisite of python3.

**Comment by katieemelianova** [comment]
Unfortunately that is still giving the same error :(

**Comment by katieemelianova** [comment]
Not sure if this is the problem - in your file you use ''python-requires" - perhaps it should be "Requires-Python"? As per:
https://packaging.python.org/guides/dropping-older-python-versions/

**Comment by arvestad** [comment]
No, within setup there should be "python_requires". 

I got some advice now, so I _think_ alv 1.0.5 solves this.

**Comment by katieemelianova** [comment]
Great, this now throws an error - thanks for fixing that.

**Comment by arvestad** [comment]
Good to hear. Thanks for your patience and help!
