### ISSUE TITLE
Update help menu and readme

### ISSUE THREAD

**Issue by schultzm** [arvestad/alv#10]
Hi arvestad,

This is a fantastic tool. I wanted to use it for reading an alignment from stdin.  I only worked out that this program does that after digging through your code in `io.py`.  Please update the help menu and readme to tell the user that if you feed it stdin via `-`, then it will work.  

Thanks again!

**Comment by arvestad** [comment]
Hi, 

I am glad you like alv! 

The feature you refer to is documented in the help text:
positional arguments:
  infile                The infile is the path to a file, or '-' if reading
                        from stdin.

I will add a note about it in the README though.

	Thanks,
	Lars

**Comment by schultzm** [comment]
Thanks!  Sorry, I overlooked that.  Best regards
