### ISSUE TITLE
Support alignment formats containing multiple alignments 

### ISSUE THREAD

**Issue by multimeric** [arvestad/alv#20]
So currently we're using: https://github.com/arvestad/alv/blob/810416385141b9ebfa1ee20b0fd85fadf0c7ab97/alv/io.py#L45

to read sequences. This will fail with say a Stockholm alignment that contains two separate alignments. Specifically I get:
```
$ alv alignment.sto
alv error: More than one record found in handle
```

I propose instead using [Bio.AlignIO.parse](https://biopython.org/docs/1.75/api/Bio.AlignIO.html#Bio.AlignIO.parse), which supports multiple sub-alignments. Then we also add a new flag such as `--alignment-index` that specifies the index of the sub-alignment to actually view. This would default to 0, indicating that it should return the 0th sub-alignment, but the user could adjust it to view other alignments.

**Comment by multimeric** [comment]
Well my original suggestion is that we only output one of the alignments, as specified by `--alignment-index`, because I figured it would be the easiest to integrate into the codebase. At least anecdotally, I generally only want to look at one of the alignments at any given time. But a possible extension could involve displaying all of them. Ideally with a more obvious delimiter than a newline.

**Comment by arvestad** [comment]
Oh yeah, now I understand. I will implement something like this.

**Comment by arvestad** [comment]
This feature is added in the release that is about to be published.
