### ISSUE TITLE
Feature request: indexed view (same as accession trimming)

### ISSUE THREAD

**Issue by rtviii** [arvestad/alv#26]
Fellas, this project is a god-send, thanks. I was a little surprised not to see the option to display only a part of the input between indices _a_ and _b_. 

I frequently work with RNA msas and those are quite long whereas i usually just want to see a vicinity of some site. I suppose this can be piped to `awk` but a native option in `alv` is much appreciated. 

Thanks again for the project, hope it flourishes. Great alternative to bloated web-viewers.

**Comment by arvestad** [comment]
Hi, I am glad you like alv! I added option -sa (--sub-alignment) for you and am preparing a new release (1.8.0) on PyPI.org.

**Comment by rtviii** [comment]
What the hell. OSS Valhalla. Thanks, Lars.
