### ISSUE TITLE
Should alignments break after X characters?

### ISSUE THREAD

**Issue by karinlag** [arvestad/alv#5]
In one of your examples, you show that the alignment wraps after X characters, similar to what it does when you look at a clustal alignment written to file. That doesn't happen when I try to use it. However, I am not sure whether this is how it should be, or if there's a bug in alv or in my environment. 

I am using conda with Python 3.6.4, with alv in its own environment.

**Comment by arvestad** [comment]
Can you give an example?

I have not written about it, but I am trying to be clever about line breaks. The alv rules are:

- Don't break in a codon. A CDS alignment is always a factor of 3 long. 
- The last alignment block should be at least 10 characters long. If the straight-forward line-breaking ends up with something shorter, then we "steal" columns from previous alignment blocks.

I have a case now where my heuristics for ideal breaking do not work very well, so some tuning is needed. More examples would help.

**Comment by karinlag** [comment]
The main issue is that it doesn't break the alignment at all, everything goes out of the screen. However, I tried on a different machine, and there line breaks works ok.

**Comment by arvestad** [comment]
What OS is it not working on? I should proceed testing this mysel on more systems. Not sure I know what to do on Windows though.

I have at least now figured out that there is Python support (since v3.3) for getting the terminal size: `shutils.get_terminal_size()`. Up until now, I have used a trick found in a gist.
