### ISSUE TITLE
I only get background colour but no base colours

### ISSUE THREAD

**Issue by roey-angel** [arvestad/alv#8]
Tried on a nucleotide alignment.

Any idea why?

**Comment by arvestad** [comment]
No idea. Have not seen that problem before. What does the data look like (if you can, please send it to me) and how did you invoke alv?

**Comment by roey-angel** [comment]
simply with `alv seqs.align`
See screenshot.

![Screenshot_20190822_152656](https://user-images.githubusercontent.com/2523883/63518496-73c58e00-c4f1-11e9-8412-05abd48a860f.png)

**Comment by arvestad** [comment]
It seems alv mistakenly believes that you have a codon alignment, and then it does not recognize any codons to color. A work around is to issue `alv -t dna seqs.align`. 

But you found a bug that I will fix and update as soon as possible. Thanks for reporting!

**Comment by roey-angel** [comment]
Ah, yes of course. The SILVA database uses the base U to indicate that this is an RNA sequence.

**Comment by arvestad** [comment]
Actuallly, alv thought it was coding DNA. :-) It should recognize it as DNA/RNA. Right now, I notice that I also cannot claim the alignment as RNA, which is another bug. So for the time being, please tell alv that you have DNA data.
