### ISSUE TITLE
Edit sequences

### ISSUE THREAD

**Issue by camilogarciabotero** [arvestad/alv#9]
Hi Lars,

Thank you for letting `alv` as an open source. I definitely have enjoyed it and have used to visualize many alignments especially as `alv -k -l <alignment> | less -RS `. However, sometimes when I spot problems in my alignment I wish I could edit it "_in situ_". Like using a terminal editor instead of less while viewing   with `alv`  

If you can suggest me anything on this regard I would really appreciate.

Cheers,
Camilo.

**Comment by arvestad** [comment]
Hi, 
I am glad you enjoy `alv`! I turn to Jalview myself when I need the editing functionality, but agree that being able to do it in the console would be preferable. Unfortunately, I don't have the time or resources (at this time) to implement that.
